#! /bin/bash
# CITS 4407 Assignment 2
# Author Zishan Luo
# Student ID 22448064


# Check the input file
if [ -z "$1" ]; then
    echo "Please input the please! "
    exit 1
fi

input_file="$1"
temp_file=$(mktemp)

# count each country's Cantril ladder score, if it is less than three, just delete it.
awk -F'\t' 'NR>1 && $8 != "" {count[$1]++} END {for (country in count) {print country "\t" count[country]; if (count[country] >= 3) print country > "'"$temp_file"'"}}' "$input_file"

echo -e "\n the number of each country Cantril ladder score："
awk -F'\t' 'NR>1 && $8 != "" {count[$1]++} END {for (country in count) print country ": " count[country]}' "$input_file"

# keeping those data in the temp_file
awk -F'\t' 'NR==1 {print} NR>1 {while (getline < "'"$temp_file"'") countries[$1]=1} NR>1 && $1 in countries {print}' "$input_file"

