#!/usr/bin/env bash
# CITS 4407 Assignment 2
# Author Zishan Luo
# Student ID 22448064

input_file="$1"
# Check the input file
if [ ! -r "$input_file" ]; then
    echo "Error: File '$input_file' does not exist or cannot be read."
    exit 1
fi


temp_file=$(mktemp)

# Calculate the average of the specified column of the given file, will use it later.
# args:
#    filename: path to the file
#    column: Which column needs to be average
function column_mean() {
    local filename=$1;
    local column=$2;
    local mean=$(awk -F '\t' "{sum += \$${column}; i++;} END {print sum/i}" $filename);
    echo $mean
    return 0;
}


# Calculate the covariance relationship between two columns
# Parameters:
#   filename: path to the file
#   column1: int
#   column2: int
function corr() {
    local filename=$1;
    local column1=$2;
    local column2=$3;

    # Calculate mean
    local mean1=$(column_mean $filename $column1);
    local mean2=$(column_mean $filename $column2);

    # Calculate correlation
    awk -F '\t' "{
        dx = \$${column1} - ${mean1};
        dy = \$${column2} - ${mean2};
        sum_dx_dy += dx * dy;
        sum_dx_square += dx * dx;
        sum_dy_square += dy * dy;
    }
    END {
            val = sum_dx_dy / sqrt(sum_dx_square * sum_dy_square);
            print val;
        }" $filename;
    return 0;
}

# Calculate the correlation between each variable and score (call the corr function)
# args:
#    filename: path to data file
cal_corr() {
    filename=$1;

    # index of each column
    local cantril_score_index=8;
    local gdp_index=4;
    local population_index=5;
    local homicide_index=6;
    local life_index=7;

    # corr score
    local r_homicide=$(corr ${filename} ${cantril_score_index} ${homicide_index});
    local r_gdp=$(corr ${filename} ${cantril_score_index} ${gdp_index});
    local r_population=$(corr ${filename} ${cantril_score_index} ${population_index});
    local r_life=$(corr ${filename} ${cantril_score_index} ${life_index});


    echo -e "${r_homicide}\t${r_gdp}\t${r_population}\t${r_life}" >> $temp_file;
}

datafile=$1;
# Calculate correlation for each countries
country_code=$(awk -F '\t' '!seen[$2]++ {print $2}' $datafile);
for code in $country_code;
do
    # Create temporary file
    country_data_file=$(mktemp);

    # Conditions for selecting a specific city; Delete empty rows
    awk -F '\t' "(\$2 == \"${code}\")" $datafile | awk -F'\t' '$8 ~ /^\s*$/ {next} 1' > $country_data_file;

    # Get the number rows
    data_count=$(awk -F '\t' 'END {print NR}' $country_data_file);

    # Calculate correlation if we have more than 3 data record
    if [ $data_count -ge 3 ]; then
        cal_corr $country_data_file;
    fi
done


#  Calculate the mean value
awk -F '\t' '{
    sum_homicide += $1;
    sum_gdp += $2;
    sum_population += $3;
    sum_life += $4;
    count++;
} END {
    mean_homicide = sum_homicide/count;
    mean_gdp = sum_gdp/count;
    mean_population = sum_population/count;
    mean_life_exp = sum_life/count;
    printf "Mean correlation of Homicide Rate with Cantril ladder is %.3f\n", mean_homicide;
    printf "Mean correlation of GDP with Cantril ladder is %.3f\n", mean_gdp;
    printf "Mean correlation of Population with Cantril ladder is %.3f\n", mean_population;
    printf "Mean correlation of Life Expectancy with Cantril ladder is %.3f\n", mean_life_exp;
}' $temp_file;



# Find the most predictive feature
awk -F '\t' '{
    sum_homicide += $1;
    sum_gdp += $2;
    sum_population += $3;
    sum_life += $4;
    count++;
} END {
    mean_homicide = sum_homicide/count;
    mean_gdp = sum_gdp/count;
    mean_population = sum_population/count;
    mean_life_exp = sum_life/count;
    printf "Homicide Rate\t%.3f\n", mean_homicide;
    printf "GDP\t%.3f\n", mean_gdp;
    printf "Population\t%.3f\n", mean_population;
    printf "Life Expectancy\t%.3f\n", mean_life_exp;
}' $temp_file |
awk -F '\t' '{
    if ($2 < 0) {
      r = -$2;
    } else {
      r = $2;
    }
    if (r > maxValue) {
      maxValue = r;
      featurename = $1;
    }
  }
  END {
    printf "Most predictive mean correlation with the Cantril ladder is %s (r = %.3f)\n", featurename, maxValue
  }'

