#! /bin/bash
# CITS 4407 Assignment 2
# Author Zishan Luo
# Student ID 22448064
invalid_format=false
# Function to check if a file is tab-separated, read the tsv header.
# Check if the input is three file or not.
if [ $# -ne 3 ]; then
    echo "Error: Expected 3 input files, received $#"
    exit 1
fi

for file in "$@"; do
    # Check if the file is tab-separated
    if ! awk -F'\t' 'NR==1 {exit !($0 ~ /\t/)}' "$file"; then
        echo "Invalid file format in $file. File is not tab-separated."
        continue
    fi

    # Check if the number of cells in each line matched the header
    num_cells_header=$(awk -F'\t' 'NR==1 {print NF; exit}' "$file")
    awk -F'\t' -v header_cells="$num_cells_header" 'NR>1 {if (NF != header_cells) print "Mismatch in number of cells in line: " $0}' "$file"
done

